test: clean
	cd api && make test
	cd paypal && make test
	cd confirmation && make test
	cd worker && make test
	cd reporter && make test
	cd scheduler && make test

prod: clean
	cd api && make prod
	cd paypal && make prod
	cd confirmation && make prod
	cd worker && make prod
	cd reporter && make prod
	cd scheduler && make prod

clean:
